### ISSUE TITLE
Suggestion: target specific img

### ISSUE THREAD

**Issue by PatrikElfstrom** [johnpolacek/imagefill.js#13]
I needed to target a specific img and not all img

    $('#header-section .image-container').imagefill({
        target: '.image'
    });

And I modded the imagefill.js and added `filter(settings.target)` on all places where the img is targeted.

**Comment by mediamix** [comment]
Thank you, @PatrikElfstrom for sharing your solution. It's exactly what I was looking for.

**Comment by johnpolacek** [comment]
I do accept pull requests! :)

**Comment by johnpolacek** [comment]
Turns out I need this for a project myself. Done!

**Comment by mediamix** [comment]
Nice! Works a treat. Thanks @johnpolacek
