### ISSUE TITLE
Console: $container.imagesLoaded is not a function

### ISSUE THREAD

**Issue by waldbach** [johnpolacek/imagefill.js#14]
```
Uncaught TypeError: $container.imagesLoaded is not a function
$.fn.imagefill @ jquery-imagefill.js:50
```

Great plugin, but I immediately get this error.
Do I need another plugin? I didn't read about this requirement though.
Maybe I should try with http://imagesloaded.desandro.com/ ?

**Comment by johnpolacek** [comment]
Yes, that's the one. In the examples, I load it from a cdn. I've updated the README with a note about the requirement.
