### ISSUE TITLE
Safari blurry images

### ISSUE THREAD

**Issue by BeatLaG** [johnpolacek/imagefill.js#7]
Hi!

I´m noticing some blurred images in Safari when using imagefill. I have checked this in other browsers and there is working perfectly. It looks like there is some scale problem with Safari. Did you notice something similar to this?

It would be really appreciate if you could provide some advice related to this issue.

Thanks for such great plugin!

**Comment by johnpolacek** [comment]
The images probably look blurry because of the way Safari renders at different scales or if the image is not of sufficient size/quality. The plugin does not do anything fancy with images that would make them fuzzy.
